import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { ContinuumConfig } from './config.js';

/** Options for project initialization */
export interface InitOptions {
  /** Target directory. Defaults to CWD. */
  dir?: string;
  /** Sandbox type to configure. */
  sandbox?: 'local' | 'docker';
  /** Skip creation if config already exists. */
  force?: boolean;
  /** Include example plan. */
  withExample?: boolean;
}

/** Result of project initialization */
export interface InitResult {
  configPath: string;
  created: string[];
  skipped: string[];
}

const EXAMPLE_PLAN = {
  plan_id: 'example-plan',
  version: '3.0',
  description: 'Example execution plan — replace with your own',
  steps: [
    {
      step_id: 'create-readme',
      type: 'create_file',
      description: 'Create a README file',
      path: 'README.md',
      content: '# My Project\n\nGenerated by Continuum.\n',
      determinism: 'guaranteed',
    },
    {
      step_id: 'verify',
      type: 'run_command',
      description: 'Verify the file was created',
      command: 'cat',
      args: ['README.md'],
      determinism: 'guaranteed',
      depends_on: ['create-readme'],
    },
  ],
  assertions: [
    {
      assertion_id: 'readme-exists',
      type: 'file_exists',
      description: 'README.md should exist after creation',
      required: true,
      stability: 'stable',
      spec: { type: 'file_exists', path: 'README.md' },
    },
  ],
};

/**
 * Generate default config for project initialization.
 */
export function generateDefaultConfig(opts?: { sandbox?: 'local' | 'docker' }): ContinuumConfig {
  const config: ContinuumConfig = {
    sandbox: opts?.sandbox ?? 'local',
    cache: { ttl_ms: 604800000 },
    execution: { max_concurrency: 4 },
    repair: { enabled_levels: [1, 2, 3] },
    retention: { max_runs: 100, max_age_days: 30 },
  };
  if (opts?.sandbox === 'docker') {
    config.docker_image = 'node:20-slim';
  }
  return config;
}

/**
 * Initialize a Continuum project in the given directory.
 * Creates .continuumrc.json and optionally an example plan.
 */
export function initProject(opts?: InitOptions): InitResult {
  const dir = opts?.dir ?? process.cwd();
  const created: string[] = [];
  const skipped: string[] = [];

  // Ensure directory exists
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  // Create .continuumrc.json
  const configPath = join(dir, '.continuumrc.json');
  if (existsSync(configPath) && !opts?.force) {
    skipped.push('.continuumrc.json');
  } else {
    const config = generateDefaultConfig({ sandbox: opts?.sandbox });
    writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf8');
    created.push('.continuumrc.json');
  }

  // Create plans/ directory
  const plansDir = join(dir, 'plans');
  if (!existsSync(plansDir)) {
    mkdirSync(plansDir, { recursive: true });
    created.push('plans/');
  } else {
    skipped.push('plans/');
  }

  // Create example plan if requested
  if (opts?.withExample) {
    const examplePath = join(plansDir, 'example.json');
    if (existsSync(examplePath) && !opts?.force) {
      skipped.push('plans/example.json');
    } else {
      writeFileSync(examplePath, JSON.stringify(EXAMPLE_PLAN, null, 2) + '\n', 'utf8');
      created.push('plans/example.json');
    }
  }

  return { configPath, created, skipped };
}
